name: aim_server_multipart
description: Multipart form data parsing for aim_server framework. Supports multipart/form-data format.
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aim_server: ^0.0.5
  mime: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
