name: _
publish_to: none
environment:
  sdk: ^3.10.0
workspace:
  - packages/aim_server
  - packages/aim_cli
  - packages/aim_server_cors
  - packages/aim_server_cookie
  - packages/aim_server_testing
  - packages/aim_server_form
  - examples/basic-sample