name: _
publish_to: none
environment:
  sdk: ^3.10.0
workspace:
  - packages/aim_server
  - packages/aim_cli
  - packages/aim_server_cors
  - packages/aim_server_cookie
  - packages/aim_server_testing
  - packages/aim_server_form
  - packages/aim_server_multipart
  - packages/aim_server_static
  - packages/aim_server_logger
  - packages/aim_server_sse
  - packages/aim_server_jwt
  - examples/basic-sample