name: aim_server_cookie
description: Cookie support for Aim framework with secure options like HttpOnly, SameSite, and expiration.
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aim_server: ^0.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
