name: aim_server_jwt
description:
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aim_server: ^0.0.6
  crypto: ^3.0.7

dev_dependencies:
  aim_server_testing: ^0.1.0
  lints: ^6.0.0
  test: ^1.25.6
