name: basic_sample
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  aim_server:
    path: ../../packages/aim_server
  aim_server_cors:
    path: ../../packages/aim_server_cors


dev_dependencies:
  aim_server_testing:
    path: ../../packages/aim_server_testing
  lints: ^6.0.0
  test: ^1.25.6

aim:
  entry: bin/main.dart
