name: aim_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
