name: aim_server_logger
description: HTTP logging middleware for aim_server with request/response details and customizable output formats.
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aim_server: 0.0.6

dev_dependencies:
  aim_server_testing: ^0.1.0
  lints: ^6.0.0
  test: ^1.25.6
