name: aim_server_cors
description: CORS middleware for the aim_server framework.
version: 0.0.1
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aim_server: 0.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
