name: aim_server
description: A lightweight, fast web framework for Dart with routing, middleware, CORS support, and hot reload during development.
version: 0.0.2
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
