name: aim_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/aim-dart/aim
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
