name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-

      - name: Get dependencies
        run: dart pub get

      - name: Run tests for aim_server
        working-directory: packages/aim_server
        run: dart test

      - name: Run tests for aim_server_form
        working-directory: packages/aim_server_form
        run: dart test

      - name: Run tests for aim_server_multipart
        working-directory: packages/aim_server_multipart
        run: dart test

      - name: Run tests for aim_server_testing
        working-directory: packages/aim_server_testing
        run: dart test

      - name: Run tests for aim_server_static
        working-directory: packages/aim_server_static
        run: dart test

      - name: Run tests for aim_server_logger
        working-directory: packages/aim_server_logger
        run: dart test

      - name: Run tests for aim_server_sse
        working-directory: packages/aim_server_sse
        run: dart test

      - name: Run tests for aim_server_jwt
        working-directory: packages/aim_server_jwt
        run: dart test

      - name: Run tests for aim_server_basic_auth
        working-directory: packages/aim_server_basic_auth
        run: dart test

      - name: Analyze aim_server
        run: dart analyze --fatal-infos

